### ISSUE TITLE
how to change redirect url?

### ISSUE THREAD

**Issue by prbl** [HenryQW/ttrss_opencc#3]
thanks for the standalone opencc image.  
one question though: is it OK to change where it redirects to? 

tried editing docker:usr/src/app/route.js. doesn't help.

**Comment by HenryQW** [comment]
Feel free to change the address and build your own Docker image, just fork this repo: https://github.com/HenryQW/OpenCC.henry.wang

https://github.com/HenryQW/OpenCC.henry.wang/blob/d266f3b75cc2785075b0a15aa087308f04377955/route.js#L45
